### ISSUE TITLE
AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'image_processor'

### ISSUE THREAD

**Issue by mzamini92** [NiuTrans/Vision-LLM-Alignment#5]
Hi, Thanks for the great work.

I have finetuned the model using [LLaVA-More](https://github.com/aimagelab/LLaVA-MORE) repository on llama3. Now when I try to adapt your code I am getting `AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'image_processor'`. I noticed that you use the transformers repository for modeling_llama which has classes like `LlavaCausalLMOutputWithPast` or `LlavaForConditionalGeneration` which they have not been used in [Here](https://github.com/aimagelab/LLaVA-MORE/blob/194f78b18bfe9a051cc0f5024bffa65344ce21f7/llava/model/language_model/llava_llama.py). So we get weight initialization error and 

```
build_model.py", line 35, in build_model
[rank2]:     image_processor = processor.image_processor
[rank2]: AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'image_processor'
```

Any help would be appreciated.
Also, if we use llava as model_architecture, these files doesn't exist on their huggingface repo:
```
            "preprocessor_config.json",
            "pytorch_model.bin"
```
preprocessor_config.json file can be found only on [llava-v1.6-vicuna-13b-hf](https://huggingface.co/llava-hf/llava-v1.6-vicuna-13b-hf/tree/main) I guess.

**Comment by wangclnlp** [comment]
Thanks for your feedback! We will test this LLaVA-More in our code. Please be patient with this result.

**Comment by wangclnlp** [comment]
Hello, we have tested the LLaVA-More model. Please use the ```llava-more``` branch. However, we only addressed the model loading part and did not verify the entire template. You’ll need to adjust the template according to your specific settings in the '[DST.py](https://github.com/wangclnlp/Vision-LLM-Alignment/blob/master/training/utils/data/DST.py#L45)' file. Let us know if you encounter any other questions during training.

**Comment by mzamini92** [comment]
thank you. will take a look at it soon. just one more question, on LLaVA model supports, if we train the LLaVA from scratch, can we run sft and rlhf for pretrained model and finetuned model? I'm just curious to see if running it on each stage would improve the results or it should be applied after finetuned model?

**Comment by wangclnlp** [comment]
When using our repository, you can run 'sft' and 'rlhf' for the pre-trained model and fine-tuned model. When executing the command 'bash run_sft.sh', the base model should be the pre-trained LLM (e.g., llama-3-7b-instruction model) with a vision encoder. When running 'rlhf', the actor model should be an sft vision LLM.

**Comment by mzamini92** [comment]
Hi again, 
I was looking at your sft, I was wondering how is your sft different from the LLaVA-NEXT finetune stage and your dpo vs their dpo. 
Thanks for your fast responses.

**Comment by wangclnlp** [comment]
Thanks for your attention! The processes of SFT and DPO in our codebase should be the same as in LLaVA. However, unlike LLaVA, our goal is to develop a tool for aligning various vision-based LLMs, and it includes SFT training, DPO training, reward model training, and PPO training. Additionally, we do not use external packages to achieve these alignment trainings, making it more beneficial for learning and understanding this alignment process :) .

**Comment by mzamini92** [comment]
Thank you. also, could you please tell me how to reproduce +VRM-Vanilla 7B, +RoVRM-Random and +RoVRM ? appreciate your always quick responses.

**Comment by Zhuzhu847** [comment]
> Thank you. also, could you please tell me how to reproduce +VRM-Vanilla 7B, +RoVRM-Random and +RoVRM ? appreciate your always quick responses.


+VRM-Vanilla refers to a VRM optimized only using a visual preference dataset (i.e., RLAIF-V preference dataset).

+RoVRM-Random involves optimizing a VRM through a three-phase progressive training process using randomly selected data. Here's how it works:

Data Selection: Randomly choose data for textual preference data, image caption-based preference data.

Training: Train the VRM using the selected data in a three-phase progressive schema.

Alignment: Utilize the trained VRM for alignment, such as using it as a reward model during the PPO and best-of-n sampling.

The training processes for RoVRM and RoVRM-Random are similar, with the key difference being the data selection approach. RoVRM-Random selects data randomly, while RoVRM employs optimal transport for data selection. Specifically, for RoVRM, we firstly choose data from the image caption-based preference dataset that has a smaller optimal transport distance to the visual preference data. Then, we select textual preference data that is closer in optimal transport distance to the selected image caption-based preference data. This approach ensures we have relevant training data for the three-phase progressive training.

For details on how to calculate the optimal transport distance and more about the training, please refer to the ```Preference Data Selection``` Section in our [paper](https://arxiv.org/abs/2408.12109). 

You can also find the weights for our RoVRM at [huggingface](https://huggingface.co/wangclnlp/robust_visual_reward_model)
