### ISSUE TITLE
Is pure textual alignment supported in your codebase (with no image input)?

### ISSUE THREAD

**Issue by hxhcreate** [NiuTrans/Vision-LLM-Alignment#6]
Is pure textual alignment supported in your codebase (with no image input)

**Comment by wangclnlp** [comment]
![image](https://github.com/user-attachments/assets/b9331b28-8a34-4bcd-ad56-786892abc43e)
This repository should support it. You just need to set the image to null, as shown in the given figure. When we process data and come across this sample, it results in an all-zero image encoding by default. For this implementation, we are referring to [llava](https://github.com/haotian-liu/LLaVA/blob/c121f0432da27facab705978f83c4ada465e46fd/llava/train/train.py#L738).

Please let us know if you encounter any problems.
